package de.mhus.nimbus.world.shared.dto;

import de.mhus.nimbus.shared.annotations.GenerateTypeScript;
import de.mhus.nimbus.shared.annotations.TypeScript;

/**
 * DTO for importing a WLayerModel from JSON data.
 * Used when importing schematic data (e.g., from schematic-tool) into a MODEL layer.
 */
@GenerateTypeScript("dto")
public record ImportLayerModelRequest(
        /**
         * JSON data containing WLayerModel structure.
         * Typically generated by schematic-tool or other model export.
         */
        String jsonData,

        /**
         * Optional: Override model name from JSON.
         */
        @TypeScript(optional = true)
        String name,

        /**
         * Optional: Override mount X coordinate from JSON.
         */
        @TypeScript(optional = true)
        Integer mountX,

        /**
         * Optional: Override mount Y coordinate from JSON.
         */
        @TypeScript(optional = true)
        Integer mountY,

        /**
         * Optional: Override mount Z coordinate from JSON.
         */
        @TypeScript(optional = true)
        Integer mountZ,

        /**
         * Optional: Override rotation from JSON (0-3, in 90 degree steps).
         */
        @TypeScript(optional = true)
        Integer rotation,

        /**
         * Optional: Override order from JSON.
         */
        @TypeScript(optional = true)
        Integer order
) {
}
