package de.mhus.nimbus.world.generator.composer.village;

import com.fasterxml.jackson.annotation.JsonInclude;
import de.mhus.nimbus.generated.types.HexVector2;
import de.mhus.nimbus.world.generator.composer.area.Area;
import de.mhus.nimbus.world.generator.composer.build.ComposeContext;
import de.mhus.nimbus.world.generator.composer.point.Direction;
import de.mhus.nimbus.world.generator.composer.point.EdgePoint;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

/**
 * Synthetic external connection point for village-to-road connections.
 * These points are placed in neighboring grids outside the village to provide
 * entry/exit points for external roads.
 *
 * VillageConnectionPoints are automatically generated by VillageExternalConnectionGenerator
 * based on the village's district count and layout.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class VillageConnectionPoint extends EdgePoint {

    /**
     * ID/Name of the village this connection point belongs to.
     */
    private String villageId;

    /**
     * Name of the internal connection point within the village that this external point connects to.
     * Used for routing streets from inside the village to this external point.
     */
    private String internalConnectionPointName;

    /**
     * Direction from village center (N, NE, E, SE, S, SW, W, NW).
     * Determines which side of the village this external connection is on.
     */
    private Direction externalDirection;

    /**
     * Grid coordinate where this external connection point is placed.
     * This is in a neighboring grid OUTSIDE the village structure.
     */
    private HexVector2 neighborGridCoordinate;

    /**
     * Whether this point was successfully placed in a neighbor grid.
     * If false, this connection point could not be placed (neighbor grid not suitable).
     */
    private boolean placedInNeighborGrid;

    /**
     * Distance from village center in number of grids.
     * Typically 1 (directly adjacent grid).
     */
    private int gridDistance;

    /**
     * Composes the position for this village external connection point.
     * Unlike EdgePoint which searches for edges, VillageConnectionPoint already has
     * a pre-determined grid coordinate (neighborGridCoordinate).
     *
     * This override returns the pre-set neighbor grid coordinate instead of
     * searching for edge positions.
     *
     * @param biome The biome this point belongs to (from biomeId)
     * @param context Context for composing
     * @return The pre-set neighborGridCoordinate as a HexLocalEdgeVector (center position)
     */
    @Override
    public de.mhus.nimbus.world.shared.world.HexLocalEdgeVector composePosition(Area biome, ComposeContext context) {
        // VillageConnectionPoint already knows its exact grid coordinate
        // Return null to signal that we don't need edge-based positioning
        // PointComposer will use neighborGridCoordinate directly
        return null;
    }

    @Override
    public String toString() {
        return String.format("VillageConnectionPoint[village=%s internal=%s direction=%s grid=[%s] placed=%b]",
                villageId, internalConnectionPointName, externalDirection,
                neighborGridCoordinate, placedInNeighborGrid);
    }
}
